config/routes.rb
Rails.application.routes.draw do
  root 'buildings#index'
  resources :stations
  resources :buildings
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/building.rb
class Building < ApplicationRecord
  has_many :stations
  validates :building, presence: true
  validates :rent, presence: true
  validates :address, presence: true
  validates :building_age, presence: true
  validates :rent, numericality:true

  accepts_nested_attributes_for :stations, reject_if: :all_blank, :allow_destroy => true

  def check
    if minutes_walk.present? && minutes_walk1.present?
      if minutes_walk <= minutes_walk1
        errors.add(:minutes_walk, 'Station one is further than station two')
      end
    end
  end
end

app/models/station.rb
class Station < ApplicationRecord
  belongs_to :building, optional: true
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  before_action :set_building, only: [:show, :edit, :update, :destroy]

  # GET /buildings
  # GET /buildings.json
  def index
    @buildings = Building.all
  end

  # GET /buildings/1
  # GET /buildings/1.json
  def show
  end

  # GET /buildings/new
  def new
    @building = Building.new
    2.times { @building.stations.build }
  end

  # GET /buildings/1/edit
  def edit
    1.times { @building.stations.build }
  end

  # POST /buildings
  # POST /buildings.json
  def create
    @building = Building.new(building_params)

    respond_to do |format|
      if @building.save
        format.html { redirect_to @building, notice: 'building was successfully created.' }
        format.json { render :show, status: :created, location: @building }
      else
        format.html { render :new }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buildings/1
  # PATCH/PUT /buildings/1.json
  def update
    respond_to do |format|
      if @building.update(building_params)
        format.html { redirect_to @building, notice: 'building was successfully updated.' }
        format.json { render :show, status: :ok, location: @building }
      else
        format.html { render :edit }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buildings/1
  # DELETE /buildings/1.json
  def destroy
    @building.destroy
    respond_to do |format|
      format.html { redirect_to buildings_url, notice: 'building was successfully destroyed.' }

    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_building
      @building = Building.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def building_params
      params.require(:building).permit(:building, :rent, :address, :building_age, :remarks, stations_attributes: [ :id,
                                                                                                                  :rail_way_line,
                                                                                                                  :station_name,
                                                                                                                  :minutes_walk ])
    end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  before_action :set_station, only: [:show, :edit, :update, :destroy]

  # GET /stations
  # GET /stations.json
  def index
    @stations = Station.all
  end

  # GET /stations/1
  # GET /stations/1.json
  def show
  end

  # GET /stations/new
  def new
    @station = Station.new
  end

  # GET /stations/1/edit
  def edit
  end

  # POST /stations
  # POST /stations.json
  def create
    @station = Station.new(station_params)

    respond_to do |format|
      if @station.save
        format.html { redirect_to @station, notice: 'Station was successfully created.' }
        format.json { render :show, status: :created, location: @station }
      else
        format.html { render :new }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stations/1
  # PATCH/PUT /stations/1.json
  def update
    respond_to do |format|
      if @station.update(station_params)
        format.html { redirect_to @station, notice: 'Station was successfully updated.' }
        format.json { render :show, status: :ok, location: @station }
      else
        format.html { render :edit }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stations/1
  # DELETE /stations/1.json
  def destroy
    @station.destroy
    respond_to do |format|
      format.html { redirect_to stations_url, notice: 'Station was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_station
      @station = Station.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def station_params
      params.require(:station).permit(:rail_way_line, :station_name, :minutes_walk, :buildingy_id)
    end
end

app/views/buildings/_form.html.erb
<div class="d-flex flex-column align-items-center mt-3">
  <div class="col-xl-7 col-lg-8 col-md-10 col-sm-11 post-card">
    <div class="card">
      <div class="card-header">
        Create New building
      </div>
      <div class="card-body">

<%= form_for(building) do |f| %>
  <% if building.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(building.errors.count, "error") %> prohibited this building from being saved:</h2>

      <ul>
      <% building.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group row mt-2">

  <div class="text-center">
  <div class="field">
    <%= f.label :building %>
    <%= f.text_field :building %>
  </div>

  <div class="field">
    <%= f.label :rent %>
    <%= f.number_field :rent %> JPY
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :building_age %>
    <%= f.number_field :building_age %>Year/Years old
  </div>

  <div class="field">
    <%= f.label :feedbacks %>
    <%= f.text_area :feedbacks %>
  </div>

  <%= f.fields_for :stations do |ff| %>
    <hr>
    <strong>Name of rail way</strong><br>
    <div class="field">
      <%= ff.label :rail_way_line, "Name of rail way line" %>
      <%= ff.text_field :rail_way_line %>
    </div>

    <div class="field">
      <%= ff.label :station_name %>
      <%= ff.text_field :station_name %>
    </div>
    <div class="field">
      <%= ff.label :minutes_walk, "How many minutes walk" %>
      <%= ff.number_field :minutes_walk %>min/mins %>
    </div>

  <% end %>

  <div class="actions">
    <%= f.submit  %>
  </div>
<% end %>

</div>

  </div>
    </div>
      </div>
        </div>
        <%= link_to 'Back', buildings_path ,  class: "btn btn-primary" %>
          </div>

app/views/buildings/edit.html.erb
<h1>Editing building</h1>

<%= render 'form', building: @building %>

<%= link_to 'Show', @building %> |
<%= link_to 'Back', buildings_path %>

app/views/buildings/index.html.erb
<p id="notice"><%= notice %></p>

<div class="d-flex flex-column align-items-center mt-3">
  <div class="col-xl-7 col-lg-8 col-md-10 col-sm-11 post-card">
    <div class="card">
      <div class="card-header">
        buildings
      </div>
      <div class="card-body">


<table>
  <thead>
    <tr>
      <th>building</th>
      <th>Rent</th>
      <th>Address</th>
      <th>Building age</th>
      <th>Feedbacks</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @buildings.each do |building| %>
      <tr>
        <td><%= building.building %></td>
        <td><%= building.rent %></td>
        <td><%= building.address %></td>
        <td><%= building.building_age %></td>
        <td><%= building.feedbacks %></td>
        <td><%= link_to 'Show', building , class: "btn btn-primary" %></td>
        <td><%= link_to 'Edit', edit_building_path(building) , class: "btn btn-primary"  %></td>
        <td><%= link_to 'Destroy', building, method: :delete, data: { confirm: 'Are you sure?' } , class: "btn "%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class="actions">
  <%= link_to 'New building', new_building_path , class: "btn btn-primary"  %>
</div>

  </div>
    </div>
      </div>
        </div>

app/views/buildings/new.html.erb
<h1>New building</h1>

<%= render 'form', building: @building %>

<%= link_to 'Back', buildings_path %>

app/views/buildings/show.html.erb
<div class="text-center">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>building:</strong>
    <%= @building.building %>
  </p>

  <p>
    <strong>Rent:</strong>
    <%= @building.rent %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= @building.address %>
  </p>

  <p>
    <strong>Building age:</strong>
    <%= @building.building_age %>
  </p>

  <p>
    <strong>Remarks:</strong>
    <%= @building.feedbacks %>
  </p>
  <hr>
  <% @building.stations.each do |poor| %>
    <h2><b>closest station </b></h2>
    <p>
      <strong>Name of railway line:</strong>
      <%= poor.rail_way_line %>
    </p>

    <p>
      <strong>Station name:</strong>
      <%= poor.station_name %>
    </p>
    <p>
    <strong>How many minutes walks:</strong>
    <%= poor.minutes_walk %>
    </p>


  <% end %>

  <%= link_to 'Edit', edit_building_path(@building) %> |
  <%= link_to 'Back', buildings_path %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MOFMOFOZI</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
  
</head>

<body>
  <%= yield %>
</body>
</html>

app/views/stations/_form.html.erb
<%= form_for(station) do |f| %>
  <% if station.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(station.errors.count, "error") %> prohibited this station from being saved:</h2>

      <ul>
      <% station.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rail_way_line %>
    <%= f.text_field :rail_way_line %>
  </div>

  <div class="field">
    <%= f.label :station_name %>
    <%= f.text_field :station_name %>
  </div>

  <div class="field">
    <%= f.label :minutes_walk %>
    <%= f.number_field :minutes_walk %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stations/edit.html.erb
<h1>Editing Station</h1>

<%= render 'form', station: @station %>

<%= link_to 'Show', @station %> |
<%= link_to 'Back', stations_path %>

app/views/stations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stations</h1>

<table>
  <thead>
    <tr>
      <th>Rail way line</th>
      <th>Station name</th>
      <th>Minutes walk</th>
      <th>building</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stations.each do |station| %>
      <tr>
        <td><%= station.rail_way_line %></td>
        <td><%= station.station_name %></td>
        <td><%= station.minutes_walk %></td>
        <td><%= station.building %></td>
        <td><%= link_to 'Show', station %></td>
        <td><%= link_to 'Edit', edit_station_path(station) %></td>
        <td><%= link_to 'Destroy', station, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Station', new_station_path %>

app/views/stations/new.html.erb
<h1>New Station</h1>

<%= render 'form', station: @station %>

<%= link_to 'Back', stations_path %>

app/views/stations/show.html.erb
 <p id="notice"><%= notice %></p>

<p>
  <strong>Rail way line:</strong>
  <%= @station.rail_way_line %>
</p>

<p>
  <strong>Station name:</strong>
  <%= @station.station_name %>
</p>

<p>
  <strong>Minutes walk:</strong>
  <%= @station.minutes_walk %>
</p>

<p>
  <strong>building:</strong>
  <%= @station.building %>
</p>

<%= link_to 'Edit', edit_station_path(@station) %> |
<%= link_to 'Back', stations_path %>